const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const AssetsPlugin = require('assets-webpack-plugin');

module.exports = {
  plugins: [
    new webpack.optimize.DedupePlugin(), // the prevents inclusion of duplicate code
    new webpack.optimize.OccurenceOrderPlugin(), // minimize chank
    new HtmlWebpackPlugin({
      template: './static/index.html', // Move the index.html file...
      minify: { // Minifying it while it is parsed
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true, // inject all files that are generated by webpack
    }),
    new webpack.optimize.UglifyJsPlugin({ // minify js files
      compress: {
        warnings: false,
      },
    }),
    new webpack.DefinePlugin({
      __DEV__: false,
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
    new AssetsPlugin({
      filename: 'assets.json',
      path: './dist',
    }),
  ],
};
